import { defineConfig, globalIgnores } from "eslint/config";
import nextVitals from "eslint-config-next/core-web-vitals";
import nextTs from "eslint-config-next/typescript";

const eslintConfig = defineConfig([
  ...nextVitals,
  ...nextTs,
  // Override default ignores of eslint-config-next.
  globalIgnores([
    // Default ignores of eslint-config-next:
    ".next/**",
    "out/**",
    "build/**",
    "next-env.d.ts",
    // Generated by `next build` via @serwist/next; not source, not committed.
    "public/sw.js",
    "public/sw.js.map",
    // Playwright output; not source, not committed.
    "playwright-report/**",
    "blob-report/**",
    "test-results/**",
  ]),
]);

export default eslintConfig;
